services:
  wghub-dev-local:
    container_name: wghub-dev-local
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      WGHUB_MONGO_CONNECTION_STRING: "mongodb://wghub-dev-mongo"
      WGHUB_MONGO_DATABASE_NAME: wghub
  wghub-dev-mongo:
    container_name: wghub-dev-mongo
    image: mongo
    volumes:
      - ./mongo.local/data:/data/db