name: Build + Push Docker Image
on:
  release:
    types: [published]
  push:
    branches:
      - 'dev'
jobs:
  build_and_push:
    name: Build Docker Image and push to GitHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@1.82.0
        with:
          targets: wasm32-unknown-unknown,x86_64-unknown-linux-musl
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Build WASM
        working-directory: ./wghub-frontend
        run: wasm-pack build --target web
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0
      - name: Install JS dependencies
        working-directory: ./wghub-ui
        run: npm install
      - name: Build frontend
        working-directory: ./wghub-ui
        run: npm run build
      - name: Set up musl
        run: |
          sudo apt update
          sudo apt install musl-dev musl-tools
      - name: Build backend
        run: cargo build --release --target x86_64-unknown-linux-musl
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}