name: Build + Push Docker Image
on:
  release:
    types: [published]
  push:
    branches:
      - 'dev'
jobs:
  build_and_push:
    name: Build Docker Image and push to GitHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Build WASM
        working-directory: ./rust/wghub-rust-web
        run: wasm-pack build --target web
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Install JS dependencies 
        run: npm install
      - name: Build app
        run: npm run build
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}